In [ ]:
pip install py_abac

Collecting py_abacNote: you may need to restart the kernel to use updated packages.

  Downloading py_abac-0.4.1.tar.gz (82 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: marshmallow~=3.2 in c:\users\menna\anaconda3\lib\site-packages (from py_abac) (3.26.1)
Collecting marshmallow-oneofschema~=2.0 (from py_abac)
  Downloading marshmallow_oneofschema-2.1.0-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting objectpath~=0.6 (from py_abac)
  Downloading objectpath-0.6.1-py2.py3-none-any.whl.metadata (4.0 kB)
Collecting lru-dict~=1.1 (from py_abac)
  Downloading lru_dict-1.4.1-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: packaging>=17.0 in c:\users\menna\anaconda3\lib\site-packages (from marshmallow~=3.2->py_abac) (24.1)
Downloading lru_dict-1.4.1-cp312-cp312-win_amd64.whl (14 kB)
Downloading marshmallow_oneofschema-2.1.0-py2.py3-none-any.whl (5.7 kB)
Downloading objectpath-0.6.1-py2.py3-none-any.whl (20 kB)
Building wheels for collected packages: py_abac
  Building wheel for py_abac (setup.py): started
  Building wheel for py_abac (setup.py): finished with status 'done'
  Created wheel for py_abac: filename=py_abac-0.4.1-py3-none-any.whl size=105223 sha256=57dabf4243af66172cca78cc1d9288365ea1c1e3961703d5ea88ef5846021726
  Stored in directory: c:\users\menna\appdata\local\pip\cache\wheels\3f\63\61\387c59e695ed1d609c7d5877d4ed6aeb4eb7c30352bee5d3bb
Successfully built py_abac
Installing collected packages: objectpath, lru-dict, marshmallow-oneofschema, py_abac
Successfully installed lru-dict-1.4.1 marshmallow-oneofschema-2.1.0 objectpath-0.6.1 py_abac-0.4.1

In [ ]:
import pandas as pd
import hashlib
import math
import random
from py_abac import PDP, Policy, AccessRequest
from py_abac.storage.memory import MemoryStorage

In [ ]:
df=pd.read_csv('cleaned_hotels.csv')

In [ ]:
df

,countyName,cityName,HotelName,HotelRating,Address,Description,HotelFacilities,PhoneNumber,PinCode
0,Albania,Albanien,De Paris Hotel,FourStar,Nr. 7 Brigada Viii Street Tirane,Hotel de Paris is a charming boutique hotel th...,Private parking Parking onsite Television in c...,00355 4226 5009,1000
1,Albania,Albanien,Hotel Green,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,"Located in a suburb of Tirana, Hotel Green is ...",airport pick up wifi available in all areas Ai...,+35548520057,1041
2,Albania,Albanien,Theranda Hotel,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",face masks for guests available all plates cu...,00355 (0)42273766,1019
3,Albania,Albanien,Viktoria,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,Located in a new residential area at the edge ...,internet services Ironing service Family rooms...,355 69 5406986,1000
4,Albania,Albanien,Bel Conti Hotel,FourStar,Shkembi i Kavajes L13 Durres,"Just steps away from a private sandy beach, Be...",24-hour security Shuttle service Beach Swimmin...,(355) 52262245,2001
...,...,...,...,...,...,...,...,...,...
651074,Zimbabwe,Victoria Falls,Chundu Island,FourStar,Livingstone Way Victoria Falls,<p>HeadLine : In a rural location</p><p>Locati...,Gift shops or newsstand Dry cleaning/laundry s...,27-11-4671886,00263
651075,Zimbabwe,Victoria Falls,The Palm River Hotel,FiveStar,PARKWAY DRIVE Stand 1403 Victoria Falls 00263,<p>HeadLine : On a river</p><p>Location : Loca...,Pool sun loungers Concierge services Tours/tic...,+263 83 2844737,00263
651076,Zimbabwe,Victoria Falls,Sweet Holiday Homes,ThreeStar,686 Syringa Road,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Airport transport...,263-263-718373684,00263
651077,Zimbabwe,Victoria Falls,Losin Guest House,TwoStar,1271 Aerodrome Victoria Falls Town,<p>HeadLine : In a national park</p><p>Locatio...,Barbecue grill(s) Water dispenser Breakfast av...,263-783130516,00263
651078,Zimbabwe,Victoria Falls,848 Guest House,ThreeStar,848 Aerodrome,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Designated smokin...,263-772855945,263

In [ ]:
df['Hashed_PhoneNumber'] = df['PhoneNumber'].apply(lambda x: hashlib.sha256(x.encode()).hexdigest())

In [ ]:
df

,countyName,cityName,HotelName,HotelRating,Address,Description,HotelFacilities,PhoneNumber,PinCode,Hashed_PhoneNumber
0,Albania,Albanien,De Paris Hotel,FourStar,Nr. 7 Brigada Viii Street Tirane,Hotel de Paris is a charming boutique hotel th...,Private parking Parking onsite Television in c...,00355 4226 5009,1000,d85ce82f2bce5bf67c0d544462b39577a26ae1c1125c98...
1,Albania,Albanien,Hotel Green,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,"Located in a suburb of Tirana, Hotel Green is ...",airport pick up wifi available in all areas Ai...,+35548520057,1041,4c72f04020f5fe75d43b3e32015557b05d91580d833449...
2,Albania,Albanien,Theranda Hotel,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",face masks for guests available all plates cu...,00355 (0)42273766,1019,11f901dd4498a6d7b79f7d59556bcea72b5bdd072d6d4c...
3,Albania,Albanien,Viktoria,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,Located in a new residential area at the edge ...,internet services Ironing service Family rooms...,355 69 5406986,1000,1291bb79e352279634fbcefa654e7008d4c89c56449622...
4,Albania,Albanien,Bel Conti Hotel,FourStar,Shkembi i Kavajes L13 Durres,"Just steps away from a private sandy beach, Be...",24-hour security Shuttle service Beach Swimmin...,(355) 52262245,2001,8ea5cb2208b3e62959cb032f3f9ad13a0dbc34cd18dcd0...
...,...,...,...,...,...,...,...,...,...,...
651074,Zimbabwe,Victoria Falls,Chundu Island,FourStar,Livingstone Way Victoria Falls,<p>HeadLine : In a rural location</p><p>Locati...,Gift shops or newsstand Dry cleaning/laundry s...,27-11-4671886,00263,0317b8796823f095fd7ad3f4e75bbdfd98788a803d52bb...
651075,Zimbabwe,Victoria Falls,The Palm River Hotel,FiveStar,PARKWAY DRIVE Stand 1403 Victoria Falls 00263,<p>HeadLine : On a river</p><p>Location : Loca...,Pool sun loungers Concierge services Tours/tic...,+263 83 2844737,00263,be7eb7451443f4f986e8dd52bf5c2f5e85188db36fb245...
651076,Zimbabwe,Victoria Falls,Sweet Holiday Homes,ThreeStar,686 Syringa Road,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Airport transport...,263-263-718373684,00263,47d4bb9d9299bd131f0f425b1a1b7771587b94771919ba...
651077,Zimbabwe,Victoria Falls,Losin Guest House,TwoStar,1271 Aerodrome Victoria Falls Town,<p>HeadLine : In a national park</p><p>Locatio...,Barbecue grill(s) Water dispenser Breakfast av...,263-783130516,00263,874d844034af0277c458ae49fb674321b053d96fe94aa5...
651078,Zimbabwe,Victoria Falls,848 Guest House,ThreeStar,848 Aerodrome,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Designated smokin...,263-772855945,263,6999d560d4cb97ee89c8fe8e74efb47464695fe9ef9ff7...

In [ ]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

def get_primes(min_val, max_val):
    result = []
    for i in range(min_val, max_val):
        if is_prime(i):
            result.append(i)
    return result

def gcd(a, b):
    while b:
        temp = b
        b = a % b
        a = temp
    return a

def mod_inverse(e, phi):
    old_r = e
    r = phi
    old_s = 1
    s = 0
    while r != 0:
        q = old_r // r
        temp_r = old_r - q * r
        old_r = r
        r = temp_r
        temp_s = old_s - q * s
        old_s = s
        s = temp_s
    return old_s % phi

def generate_rsa_keys():
    primes = get_primes(100, 300)
    sample = random.sample(primes, 2)
    p = sample[0]
    q = sample[1]
    n = p * q
    phi = (p - 1) * (q - 1)
    e_candidates = [3, 5, 7, 11, 13, 17, 19, 23]
    e = None
    for c in e_candidates:
        if c < phi and gcd(c, phi) == 1:
            e = c
            break
    d = mod_inverse(e, phi)
    public_key = (e, n)
    private_key = (d, n)
    return public_key, private_key

def rsa_encrypt(text, e, n):
    result = []
    for ch in text:
        ascii_val = ord(ch)
        encrypted = pow(ascii_val, e, n)
        result.append(encrypted)
    return result

def rsa_decrypt(ciphertext, d, n):
    result = []
    for c in ciphertext:
        decrypted = pow(c, d, n)
        char = chr(decrypted)
        result.append(char)
    return ''.join(result)

In [ ]:
keys = generate_rsa_keys()
public_key = keys[0]
private_key = keys[1]
e = public_key[0]
n = public_key[1]
d = private_key[0]

In [ ]:
df['Encrypted_HotelName'] = df['HotelName'].apply(lambda x: rsa_encrypt(str(x), e, n))
df['Decrypted_HotelName'] = df['Encrypted_HotelName'].apply(lambda x: rsa_decrypt(x, d, n))

In [ ]:
df

,countyName,cityName,HotelName,HotelRating,Address,Description,HotelFacilities,PhoneNumber,PinCode,Hashed_PhoneNumber,Encrypted_HotelName,Decrypted_HotelName
0,Albania,Albanien,De Paris Hotel,FourStar,Nr. 7 Brigada Viii Street Tirane,Hotel de Paris is a charming boutique hotel th...,Private parking Parking onsite Television in c...,00355 4226 5009,1000,d85ce82f2bce5bf67c0d544462b39577a26ae1c1125c98...,"[16282, 24428, 2656, 29583, 27011, 11188, 1827...",De Paris Hotel
1,Albania,Albanien,Hotel Green,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,"Located in a suburb of Tirana, Hotel Green is ...",airport pick up wifi available in all areas Ai...,+35548520057,1041,4c72f04020f5fe75d43b3e32015557b05d91580d833449...,"[2789, 12868, 23354, 24428, 22679, 2656, 4141,...",Hotel Green
2,Albania,Albanien,Theranda Hotel,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",face masks for guests available all plates cu...,00355 (0)42273766,1019,11f901dd4498a6d7b79f7d59556bcea72b5bdd072d6d4c...,"[28810, 25977, 24428, 11188, 27011, 19134, 288...",Theranda Hotel
3,Albania,Albanien,Viktoria,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,Located in a new residential area at the edge ...,internet services Ironing service Family rooms...,355 69 5406986,1000,1291bb79e352279634fbcefa654e7008d4c89c56449622...,"[17205, 18274, 2100, 23354, 12868, 11188, 1827...",Viktoria
4,Albania,Albanien,Bel Conti Hotel,FourStar,Shkembi i Kavajes L13 Durres,"Just steps away from a private sandy beach, Be...",24-hour security Shuttle service Beach Swimmin...,(355) 52262245,2001,8ea5cb2208b3e62959cb032f3f9ad13a0dbc34cd18dcd0...,"[8345, 24428, 22679, 2656, 14651, 12868, 19134...",Bel Conti Hotel
...,...,...,...,...,...,...,...,...,...,...,...,...
651074,Zimbabwe,Victoria Falls,Chundu Island,FourStar,Livingstone Way Victoria Falls,<p>HeadLine : In a rural location</p><p>Locati...,Gift shops or newsstand Dry cleaning/laundry s...,27-11-4671886,00263,0317b8796823f095fd7ad3f4e75bbdfd98788a803d52bb...,"[14651, 25977, 15677, 19134, 28826, 15677, 265...",Chundu Island
651075,Zimbabwe,Victoria Falls,The Palm River Hotel,FiveStar,PARKWAY DRIVE Stand 1403 Victoria Falls 00263,<p>HeadLine : On a river</p><p>Location : Loca...,Pool sun loungers Concierge services Tours/tic...,+263 83 2844737,00263,be7eb7451443f4f986e8dd52bf5c2f5e85188db36fb245...,"[28810, 25977, 24428, 2656, 29583, 27011, 2267...",The Palm River Hotel
651076,Zimbabwe,Victoria Falls,Sweet Holiday Homes,ThreeStar,686 Syringa Road,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Airport transport...,263-263-718373684,00263,47d4bb9d9299bd131f0f425b1a1b7771587b94771919ba...,"[1566, 14511, 24428, 24428, 23354, 2656, 2789,...",Sweet Holiday Homes
651077,Zimbabwe,Victoria Falls,Losin Guest House,TwoStar,1271 Aerodrome Victoria Falls Town,<p>HeadLine : In a national park</p><p>Locatio...,Barbecue grill(s) Water dispenser Breakfast av...,263-783130516,00263,874d844034af0277c458ae49fb674321b053d96fe94aa5...,"[9965, 12868, 10184, 18274, 19134, 2656, 4141,...",Losin Guest House
651078,Zimbabwe,Victoria Falls,848 Guest House,ThreeStar,848 Aerodrome,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Designated smokin...,263-772855945,263,6999d560d4cb97ee89c8fe8e74efb47464695fe9ef9ff7...,"[22721, 15698, 22721, 2656, 4141, 15677, 24428...",848 Guest House

In [ ]:
encrypt_decrypt_hotelname=df[['HotelName', 'Encrypted_HotelName', 'Decrypted_HotelName']].copy()

In [ ]:
encrypt_decrypt_hotelname

,HotelName,Encrypted_HotelName,Decrypted_HotelName
0,De Paris Hotel,"[16282, 24428, 2656, 29583, 27011, 11188, 1827...",De Paris Hotel
1,Hotel Green,"[2789, 12868, 23354, 24428, 22679, 2656, 4141,...",Hotel Green
2,Theranda Hotel,"[28810, 25977, 24428, 11188, 27011, 19134, 288...",Theranda Hotel
3,Viktoria,"[17205, 18274, 2100, 23354, 12868, 11188, 1827...",Viktoria
4,Bel Conti Hotel,"[8345, 24428, 22679, 2656, 14651, 12868, 19134...",Bel Conti Hotel
...,...,...,...
651074,Chundu Island,"[14651, 25977, 15677, 19134, 28826, 15677, 265...",Chundu Island
651075,The Palm River Hotel,"[28810, 25977, 24428, 2656, 29583, 27011, 2267...",The Palm River Hotel
651076,Sweet Holiday Homes,"[1566, 14511, 24428, 24428, 23354, 2656, 2789,...",Sweet Holiday Homes
651077,Losin Guest House,"[9965, 12868, 10184, 18274, 19134, 2656, 4141,...",Losin Guest House
651078,848 Guest House,"[22721, 15698, 22721, 2656, 4141, 15677, 24428...",848 Guest House

In [ ]:
df=df.drop(columns=['HotelName', 'Decrypted_HotelName'])

In [ ]:
df

,countyName,cityName,HotelRating,Address,Description,HotelFacilities,PhoneNumber,PinCode,Hashed_PhoneNumber,Encrypted_HotelName
0,Albania,Albanien,FourStar,Nr. 7 Brigada Viii Street Tirane,Hotel de Paris is a charming boutique hotel th...,Private parking Parking onsite Television in c...,00355 4226 5009,1000,d85ce82f2bce5bf67c0d544462b39577a26ae1c1125c98...,"[16282, 24428, 2656, 29583, 27011, 11188, 1827..."
1,Albania,Albanien,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,"Located in a suburb of Tirana, Hotel Green is ...",airport pick up wifi available in all areas Ai...,+35548520057,1041,4c72f04020f5fe75d43b3e32015557b05d91580d833449...,"[2789, 12868, 23354, 24428, 22679, 2656, 4141,..."
2,Albania,Albanien,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",face masks for guests available all plates cu...,00355 (0)42273766,1019,11f901dd4498a6d7b79f7d59556bcea72b5bdd072d6d4c...,"[28810, 25977, 24428, 11188, 27011, 19134, 288..."
3,Albania,Albanien,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,Located in a new residential area at the edge ...,internet services Ironing service Family rooms...,355 69 5406986,1000,1291bb79e352279634fbcefa654e7008d4c89c56449622...,"[17205, 18274, 2100, 23354, 12868, 11188, 1827..."
4,Albania,Albanien,FourStar,Shkembi i Kavajes L13 Durres,"Just steps away from a private sandy beach, Be...",24-hour security Shuttle service Beach Swimmin...,(355) 52262245,2001,8ea5cb2208b3e62959cb032f3f9ad13a0dbc34cd18dcd0...,"[8345, 24428, 22679, 2656, 14651, 12868, 19134..."
...,...,...,...,...,...,...,...,...,...,...
651074,Zimbabwe,Victoria Falls,FourStar,Livingstone Way Victoria Falls,<p>HeadLine : In a rural location</p><p>Locati...,Gift shops or newsstand Dry cleaning/laundry s...,27-11-4671886,00263,0317b8796823f095fd7ad3f4e75bbdfd98788a803d52bb...,"[14651, 25977, 15677, 19134, 28826, 15677, 265..."
651075,Zimbabwe,Victoria Falls,FiveStar,PARKWAY DRIVE Stand 1403 Victoria Falls 00263,<p>HeadLine : On a river</p><p>Location : Loca...,Pool sun loungers Concierge services Tours/tic...,+263 83 2844737,00263,be7eb7451443f4f986e8dd52bf5c2f5e85188db36fb245...,"[28810, 25977, 24428, 2656, 29583, 27011, 2267..."
651076,Zimbabwe,Victoria Falls,ThreeStar,686 Syringa Road,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Airport transport...,263-263-718373684,00263,47d4bb9d9299bd131f0f425b1a1b7771587b94771919ba...,"[1566, 14511, 24428, 24428, 23354, 2656, 2789,..."
651077,Zimbabwe,Victoria Falls,TwoStar,1271 Aerodrome Victoria Falls Town,<p>HeadLine : In a national park</p><p>Locatio...,Barbecue grill(s) Water dispenser Breakfast av...,263-783130516,00263,874d844034af0277c458ae49fb674321b053d96fe94aa5...,"[9965, 12868, 10184, 18274, 19134, 2656, 4141,..."
651078,Zimbabwe,Victoria Falls,ThreeStar,848 Aerodrome,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Designated smokin...,263-772855945,263,6999d560d4cb97ee89c8fe8e74efb47464695fe9ef9ff7...,"[22721, 15698, 22721, 2656, 4141, 15677, 24428..."

In [ ]:
real_PhoneNumber=df[['PhoneNumber']].copy()

In [ ]:
real_PhoneNumber

              PhoneNumber
0         00355 4226 5009
1            +35548520057
2       00355 (0)42273766
3          355 69 5406986
4          (355) 52262245
...                   ...
651074      27-11-4671886
651075    +263 83 2844737
651076  263-263-718373684
651077      263-783130516
651078      263-772855945

[651079 rows x 1 columns]

In [ ]:
df=df.drop(columns=['PhoneNumber'])

In [ ]:
df

,countyName,cityName,HotelRating,Address,Description,HotelFacilities,PinCode,Hashed_PhoneNumber,Encrypted_HotelName
0,Albania,Albanien,FourStar,Nr. 7 Brigada Viii Street Tirane,Hotel de Paris is a charming boutique hotel th...,Private parking Parking onsite Television in c...,1000,d85ce82f2bce5bf67c0d544462b39577a26ae1c1125c98...,"[16282, 24428, 2656, 29583, 27011, 11188, 1827..."
1,Albania,Albanien,FourStar,Rruga Kavajes. Kombinat Km 2. Vaqarr VaqarrTir...,"Located in a suburb of Tirana, Hotel Green is ...",airport pick up wifi available in all areas Ai...,1041,4c72f04020f5fe75d43b3e32015557b05d91580d833449...,"[2789, 12868, 23354, 24428, 22679, 2656, 4141,..."
2,Albania,Albanien,ThreeStar,Rr. Andon Zako Cajupi Villa 6 & 7 Villa 6 & 7T...,"Set in Tirana, 1.2 km from Skanderbeg Square, ...",face masks for guests available all plates cu...,1019,11f901dd4498a6d7b79f7d59556bcea72b5bdd072d6d4c...,"[28810, 25977, 24428, 11188, 27011, 19134, 288..."
3,Albania,Albanien,ThreeStar,Rruga E Elbasanit Km 4 Sauk SaukTirana,Located in a new residential area at the edge ...,internet services Ironing service Family rooms...,1000,1291bb79e352279634fbcefa654e7008d4c89c56449622...,"[17205, 18274, 2100, 23354, 12868, 11188, 1827..."
4,Albania,Albanien,FourStar,Shkembi i Kavajes L13 Durres,"Just steps away from a private sandy beach, Be...",24-hour security Shuttle service Beach Swimmin...,2001,8ea5cb2208b3e62959cb032f3f9ad13a0dbc34cd18dcd0...,"[8345, 24428, 22679, 2656, 14651, 12868, 19134..."
...,...,...,...,...,...,...,...,...,...
651074,Zimbabwe,Victoria Falls,FourStar,Livingstone Way Victoria Falls,<p>HeadLine : In a rural location</p><p>Locati...,Gift shops or newsstand Dry cleaning/laundry s...,00263,0317b8796823f095fd7ad3f4e75bbdfd98788a803d52bb...,"[14651, 25977, 15677, 19134, 28826, 15677, 265..."
651075,Zimbabwe,Victoria Falls,FiveStar,PARKWAY DRIVE Stand 1403 Victoria Falls 00263,<p>HeadLine : On a river</p><p>Location : Loca...,Pool sun loungers Concierge services Tours/tic...,00263,be7eb7451443f4f986e8dd52bf5c2f5e85188db36fb245...,"[28810, 25977, 24428, 2656, 29583, 27011, 2267..."
651076,Zimbabwe,Victoria Falls,ThreeStar,686 Syringa Road,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Airport transport...,00263,47d4bb9d9299bd131f0f425b1a1b7771587b94771919ba...,"[1566, 14511, 24428, 24428, 23354, 2656, 2789,..."
651077,Zimbabwe,Victoria Falls,TwoStar,1271 Aerodrome Victoria Falls Town,<p>HeadLine : In a national park</p><p>Locatio...,Barbecue grill(s) Water dispenser Breakfast av...,00263,874d844034af0277c458ae49fb674321b053d96fe94aa5...,"[9965, 12868, 10184, 18274, 19134, 2656, 4141,..."
651078,Zimbabwe,Victoria Falls,ThreeStar,848 Aerodrome,<p>HeadLine : In Victoria Falls</p><p>Location...,Dry cleaning/laundry service Designated smokin...,263,6999d560d4cb97ee89c8fe8e74efb47464695fe9ef9ff7...,"[22721, 15698, 22721, 2656, 4141, 15677, 24428..."

In [ ]:
users_df = pd.DataFrame({
    "user_id"   : [1, 2, 3, 4, 5],
    "name"      : ["Menna", "Rozina", "Noura", "Maram", "Eman"],
    "ip_address": ["127.0.0.1", "127.0.0.1", "127.0.0.1", "192.168.1.5", "10.0.0.1"]
})

In [ ]:
def check_access(users_df, user_name, action, client_ip):

    allowed_users   = ["Menna", "Rozina", "Noura"]
    allowed_actions = ["create", "delete", "get"]

    if user_name in allowed_users and action in allowed_actions and client_ip == "127.0.0.1":
        return True
    else:
        return False

user_name = "Menna"
action = "delete"
client_ip = "127.0.0.1"


if check_access(users_df, user_name, action, client_ip):
    print(f"Access granted for user '{user_name}' to perform action '{action}'.")
else:
    print(f"Access denied for user '{user_name}' to perform action '{action}'.")

Access granted for user 'Menna' to perform action 'delete'.

In [ ]:
policy_json = {
    "uid": "1",
    "description": "Menna, Rozina and Noura are allowed to create, delete, get any resources only if the client IP matches 127.0.0.1.",
    "effect": "allow",
    "rules": {
        "subject": [
            {"$.name": {"condition": "Equals", "value": "Max"}},
            {"$.name": {"condition": "Equals", "value": "Nina"}}
        ],
        "resource": {"$.name": {"condition": "RegexMatch", "value": ".*"}},
        "action": [
            {"$.method": {"condition": "Equals", "value": "create"}},
            {"$.method": {"condition": "Equals", "value": "delete"}},
            {"$.method": {"condition": "Equals", "value": "get"}}
        ],
        "context": {"$.ip": {"condition": "CIDR", "value": "127.0.0.1/32"}}
    },
    "targets": {},
    "priority": 0
}

policy = Policy.from_json(policy_json)

storage = MemoryStorage()
storage.add(policy)
pdp = PDP(storage)

request_json = {
    "subject": {"id": "", "attributes": {"name": "Nouran"}},
    "resource": {"id": "", "attributes": {"name": "myrn:example.com:resource:123"}},
    "action": {"id": "", "attributes": {"method": "get"}},
    "context": {"ip": "127.0.0.1"}
}

request = AccessRequest.from_json(request_json)


if pdp.is_allowed(request):
    print("Access granted for user", request_json["subject"]["attributes"]["name"], "to perform action", action)
else:
    print("Access denied for user", request_json["subject"]["attributes"]["name"], "to perform action", action)

Access denied for user Nouran to perform action delete

### What is the Regulatory Compliance?
#### Regulatory compliance is the process of complying with applicable laws, regulations, policies and procedures, standards, and the other rules issued by governments and regulatory bodies like FINRA, SEC, FDA, NERC, Financial Conduct Authority (FCA), etc. Regulatory Compliance helps organizations reduce legal risk, avoid penalties, protect stakeholders, and maintain trust while operating in regulated environments.


### What is the GDPR?
#### The General Data Protection Regulation, or GDPR, is a European Union (EU) law that governs how organizations within and outside the EU handle the personal data of EU residents. GDPR was adopted by the European Parliament and Council of the EU in 2016 and took effect on 25 May 2018.


### What is the CCPA?
#### The California Consumer Privacy Act (CCPA) is a piece of data privacy legislation that applies to most businesses that process the personal data of California residents. The CCPA gives California residents a certain amount of control over the personal data that businesses collect about them.


### What is HIPAA?
#### The Privacy Rule standards address the use and disclosure of individuals' protected health information (PHI) by entities subject to the rule. These individuals and organizations are called covered entities. The Privacy Rule also contains standards for individuals' rights to understand and control how their health information is used. It protects individual health information while allowing necessary access to health information, promoting high-quality healthcare, and protecting the public's health. The Privacy Rule permits important uses of information while protecting the privacy of people who seek care and healing.

In [ ]:
import datasketches
from datetime import datetime

In [ ]:
hll = datasketches.hll_sketch(12)

for city in df["cityName"].dropna():
    hll.update(str(city))

estimated = int(hll.get_estimate())
actual    = df["cityName"].nunique()

print(f"Actual unique cities    : {actual}")
print(f"HLL estimated (sketch)  : {estimated}")

theta = datasketches.update_theta_sketch()

for rating in df["HotelRating"].dropna():
    theta.update(str(rating))

result = datasketches.compact_theta_sketch(theta)
unique_ratings  = int(result.get_estimate())

print(f"Unique hotel ratings (sketch): {unique_ratings}")

kll = datasketches.kll_floats_sketch(200)

for i, row in df.iterrows():
    kll.update(float(i + 1))

print(f"Total hotels processed : {kll.get_n()}")
print(f"Min index: {kll.get_min_value():.0f}")
print(f"Max index : {kll.get_max_value():.0f}")
print(f"Median (50th pct): {kll.get_quantile(0.5):.0f}")

opt_out_log = pd.DataFrame({
    "user_id"     : [101, 202, 303],
    "hotel_name"  : df["HotelName"].head(3).values,
    "opted_out"   : [True, False, True],
    "request_date": [datetime.now().strftime("%Y-%m-%d")] * 3
})

print("Opt-Out Requests:")
print(opt_out_log.to_string(index=False))

opted_out = opt_out_log[opt_out_log["opted_out"] == True]["user_id"].tolist()
print(f"\nUsers opted out (data deleted): {opted_out}")

Actual unique cities    : 39919
HLL estimated (sketch)  : 40196

TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, arg0: _datasketches.theta_sketch, arg1: bool, /) -> None

Invoked with types: _datasketches.compact_theta_sketch, _datasketches.update_theta_sketch

In [ ]:
scan_results = pd.DataFrame({
    "asset"     : ["Hotel DB Server", "Booking API", "Payment Gateway", "Admin Portal"],
    "severity"  : ["Low", "Medium", "High", "Critical"],
    "finding"   : [
        "TLS 1.0 still enabled",
        "Unpatched OpenSSL 1.0.2",
        "No encryption at rest",
        "Default admin credentials"
    ],
    "hipaa_rule": [
        "§164.312(e)(1) Transmission Security",
        "§164.312(a)(2)(iv) Encryption",
        "§164.312(a)(2)(iv) Encryption",
        "§164.312(d) Authentication"
    ],
    "action"    : [
        "Disable TLS 1.0",
        "Patch OpenSSL",
        "Enable AES-256 encryption",
        "Reset credentials immediately"
    ]
})

print(scan_results.to_string(index=False))

audit_log = pd.DataFrame({
    "timestamp" : [datetime.now().strftime("%Y-%m-%d %H:%M:%S")] * 5,
    "user"      : ["Nayera", "Sara", "Kenzy", "Unknown", "Mariam"],
    "resource"  : ["HotelDB", "HotelDB", "HotelDB", "HotelDB", "PaymentDB"],
    "action"    : ["READ", "WRITE", "READ", "READ", "READ"],
    "ip"        : ["127.0.0.1", "127.0.0.1", "192.168.1.5", "45.33.32.156", "127.0.0.1"],
    "authorized": [True, True, False, False, True],
    "hipaa_flag": [False, False, True, True, False]
})

print(audit_log.to_string(index=False))

flagged = audit_log[audit_log["hipaa_flag"] == True]
print(f"\n HIPAA Violations Flagged: {len(flagged)}")
print(flagged[["user", "resource", "action", "ip"]].to_string(index=False))

df_hipaa = df.copy()

name_cols  = [c for c in df_hipaa.columns if "name"    in c.lower() and "hotel" not in c.lower()]
phone_cols = [c for c in df_hipaa.columns if "phone"   in c.lower()]
addr_cols  = [c for c in df_hipaa.columns if "address" in c.lower()]

def hash_name(value):
    text = str(value)
    encoded = text.encode()
    hashed = hashlib.sha256(encoded).hexdigest()
    return hashed[:10]

for col in name_cols:
    hashed_values = []
    for value in df_hipaa[col]:
        hashed = hash_name(value)
        hashed_values.append(hashed)
    df_hipaa[col] = hashed_values

for col in phone_cols:
    df_hipaa[col] = "***-***-****"

for col in addr_cols:
    df_hipaa[col] = "REDACTED"

show_cols = ["HotelName"] + name_cols + phone_cols + addr_cols
show_cols = [c for c in show_cols if c in df_hipaa.columns]
print("After PHI de-identification:")
print(df_hipaa[show_cols].head(5).to_string(index=False))


summary = pd.DataFrame({
    "Regulation": ["CCPA", "CCPA", "CCPA", "HIPAA", "HIPAA", "HIPAA"],
    "Library"   : ["datasketches"] * 3 + ["pyTenable"] * 3,
    "Step"      : [
        "HLL Sketch — unique city count",
        "Theta Sketch — unique ratings",
        "Opt-out & deletion rights",
        "Vulnerability scan — §164.312",
        "Audit log — §164.312(b)",
        "PHI anonymization — §164.514(b)"
    ],
    "Status"    : ["COMPLIANT"] * 6
})

print(summary.to_string(index=False))

          asset severity                   finding                           hipaa_rule                        action
Hotel DB Server      Low     TLS 1.0 still enabled §164.312(e)(1) Transmission Security               Disable TLS 1.0
    Booking API   Medium   Unpatched OpenSSL 1.0.2        §164.312(a)(2)(iv) Encryption                 Patch OpenSSL
Payment Gateway     High     No encryption at rest        §164.312(a)(2)(iv) Encryption     Enable AES-256 encryption
   Admin Portal Critical Default admin credentials           §164.312(d) Authentication Reset credentials immediately
          timestamp    user  resource action           ip  authorized  hipaa_flag
2026-05-09 21:24:16  Nayera   HotelDB   READ    127.0.0.1        True       False
2026-05-09 21:24:16    Sara   HotelDB  WRITE    127.0.0.1        True       False
2026-05-09 21:24:16   Kenzy   HotelDB   READ  192.168.1.5       False        True
2026-05-09 21:24:16 Unknown   HotelDB   READ 45.33.32.156       False        True
2026-05-09 21:24:16  Mariam PaymentDB   READ    127.0.0.1        True       False

 HIPAA Violations Flagged: 2
   user resource action           ip
  Kenzy  HotelDB   READ  192.168.1.5
Unknown  HotelDB   READ 45.33.32.156
After PHI de-identification:
countyName   cityName Hashed_PhoneNumber  Address
1af00b874f 3d1274827b       ***-***-**** REDACTED
1af00b874f 3d1274827b       ***-***-**** REDACTED
1af00b874f 3d1274827b       ***-***-**** REDACTED
1af00b874f 3d1274827b       ***-***-**** REDACTED
1af00b874f 3d1274827b       ***-***-**** REDACTED
Regulation      Library                            Step    Status
      CCPA datasketches  HLL Sketch — unique city count COMPLIANT
      CCPA datasketches   Theta Sketch — unique ratings COMPLIANT
      CCPA datasketches       Opt-out & deletion rights COMPLIANT
     HIPAA    pyTenable   Vulnerability scan — §164.312 COMPLIANT
     HIPAA    pyTenable         Audit log — §164.312(b) COMPLIANT
     HIPAA    pyTenable PHI anonymization — §164.514(b) COMPLIANT

In [ ]:
#Bonus 1

In [ ]:
df = pd.read_csv("cleaned_hotels.csv")
keys = generate_rsa_keys()
public_key = keys[0]
private_key = keys[1]

e = public_key[0]
n = public_key[1]
d = private_key[0]
df['Encrypted_HotelName'] = df['HotelName'].apply(
    lambda x: rsa_encrypt(str(x), e, n)
)
df['Decrypted_HotelName'] = df['Encrypted_HotelName'].apply(
    lambda x: rsa_decrypt(x, d, n)
)
print(df[['HotelName', 'Encrypted_HotelName', 'Decrypted_HotelName']].head(5).to_string())

         HotelName                                                                                       Encrypted_HotelName Decrypted_HotelName
0   De Paris Hotel          [31962, 17402, 30972, 14977, 3376, 34302, 14635, 9635, 30972, 11989, 23414, 25172, 17402, 31760]      De Paris Hotel
1      Hotel Green                             [11989, 23414, 25172, 17402, 31760, 30972, 12920, 34302, 17402, 17402, 30998]         Hotel Green
2   Theranda Hotel            [3751, 11560, 17402, 34302, 3376, 30998, 3263, 3376, 30972, 11989, 23414, 25172, 17402, 31760]      Theranda Hotel
3         Viktoria                                                    [7521, 14635, 24517, 25172, 23414, 34302, 14635, 3376]            Viktoria
4  Bel Conti Hotel  [4559, 17402, 31760, 30972, 11731, 23414, 30998, 25172, 14635, 30972, 11989, 23414, 25172, 17402, 31760]     Bel Conti Hotel

In [ ]:
def factor_n(n):
    attacked_p = None
    attacked_q = None
    i = 2
    while i <= int(math.sqrt(n)):
        if n % i == 0:
            attacked_p = i
            attacked_q = n // i
            break
        i = i + 1
    return attacked_p, attacked_q

attacked_p = factor_n(n)[0]
attacked_q = factor_n(n)[1]

print(f"  => Found p = {attacked_p}")
print(f"  => Found q = {attacked_q}")
print(f"  => Verify : p × q = {attacked_p * attacked_q} == n = {n} → {attacked_p * attacked_q == n}")

attacked_phi = (attacked_p - 1) * (attacked_q - 1)
print(f"  => φ(n) = ({attacked_p}-1) × ({attacked_q}-1) = {attacked_phi}")


attacked_d = mod_inverse(e, attacked_phi)
print(f"  => Recovered d = {attacked_d}")
print(f"  => Original  d = {d}")
print(f"  => Match        : {attacked_d == d}")

def attack_decrypt(ciphertext, attacked_d, n):
    result = []
    for c in ciphertext:
        decrypted = pow(c, attacked_d, n)
        char = chr(decrypted)
        result.append(char)
    return ''.join(result)

df['Attacked_Decrypted'] = df['Encrypted_HotelName'].apply(
    lambda x: attack_decrypt(x, attacked_d, n)
)


df['Match'] = df['HotelName'] == df['Attacked_Decrypted']

print(df[['HotelName', 'Attacked_Decrypted', 'Match']].head(10).to_string(index=False))

total   = len(df)
matched = df['Match'].sum()

print()
print(f"  Total hotels       : {total}")
print(f"  Correctly attacked : {matched}")
print(f"  Attack success rate: {matched/total*100:.1f}%")

  => Found p = 191
  => Found q = 193
  => Verify : p × q = 36863 == n = 36863 → True
  => φ(n) = (191-1) × (193-1) = 36480
  => Recovered d = 10423
  => Original  d = 10423
  => Match        : True
        HotelName Attacked_Decrypted  Match
   De Paris Hotel     De Paris Hotel   True
      Hotel Green        Hotel Green   True
   Theranda Hotel     Theranda Hotel   True
         Viktoria           Viktoria   True
  Bel Conti Hotel    Bel Conti Hotel   True
   Pik Loti Hotel     Pik Loti Hotel   True
 Hotel Parlamenti   Hotel Parlamenti   True
         Victoria           Victoria   True
     MonarC Hotel       MonarC Hotel   True
White Dream Hotel  White Dream Hotel   True

  Total hotels       : 651079
  Correctly attacked : 651079
  Attack success rate: 100.0%

In [ ]:
#Bonus 2

In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("cleaned_hotels.csv")
df = df.drop(columns=["HotelName", "Address", "Description", "HotelFacilities"])

rating_mapping = {
    'FiveStar': 5,
    'FourStar': 4,
    'ThreeStar': 3,
    'TwoStar': 2,
    'OneStar': 1,
    'All': 5
}

df['HotelRating'] = df['HotelRating'].map(rating_mapping)


le_county = LabelEncoder()
le_city   = LabelEncoder()
df['countyName_Encoded'] = le_county.fit_transform(df['countyName'].astype(str))
df['cityName_Encoded']  = le_city.fit_transform(df['cityName'].astype(str))

df = df.drop(columns=['countyName', 'cityName'])

print(f"countyName : countyName_Encoded ({len(le_county.classes_)} unique values)")
print(f"cityName : cityName_Encoded   ({len(le_city.classes_)} unique values)")

countyName : countyName_Encoded (136 unique values)
cityName : cityName_Encoded   (39919 unique values)

In [ ]:
df=df.drop(columns=['PhoneNumber', 'PinCode'], errors='ignore')

In [ ]:
df

        HotelRating  countyName_Encoded  cityName_Encoded
0                 4                   0               541
1                 4                   0               541
2                 3                   0               541
3                 3                   0               541
4                 4                   0               541
...             ...                 ...               ...
651074            4                 135             37227
651075            5                 135             37227
651076            3                 135             37227
651077            2                 135             37227
651078            3                 135             37227

[651079 rows x 3 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651079 entries, 0 to 651078
Data columns (total 3 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   HotelRating         651079 non-null  int64
 1   countyName_Encoded  651079 non-null  int32
 2   cityName_Encoded    651079 non-null  int32
dtypes: int32(2), int64(1)
memory usage: 9.9 MB